version: '3.8'

services:
  api:
    build: .
    ports:
      - "3000:3000"
    command: bun run --watch src/app.ts
    environment:
      DATABASE_URL: postgresql://prisma:prisma@db:5432/library?schema=public
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: library
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  prisma:
    build: .
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      DATABASE_URL: postgresql://prisma:prisma@db:5432/library?schema=public
    command: bun x prisma migrate deploy

volumes:
  postgres_data: